// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PedidosSuplidores_Blazor.DAL;

namespace PedidosSuplidores_Blazor.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("PedidosSuplidores_Blazor.Models.Ordenes", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuplidorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdenId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("PedidosSuplidores_Blazor.Models.OrdenesDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("OrdenesDetalle");
                });

            modelBuilder.Entity("PedidosSuplidores_Blazor.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Inventario")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Costo = 23m,
                            Descripcion = "Arroz Selecto",
                            Inventario = 100m
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 50m,
                            Descripcion = "Habichuelas rojas",
                            Inventario = 40m
                        },
                        new
                        {
                            ProductoId = 3,
                            Costo = 30m,
                            Descripcion = "CocaCola",
                            Inventario = 15m
                        },
                        new
                        {
                            ProductoId = 4,
                            Costo = 8m,
                            Descripcion = "Galletas Oreo",
                            Inventario = 24m
                        },
                        new
                        {
                            ProductoId = 5,
                            Costo = 20m,
                            Descripcion = "Doritos Rojos",
                            Inventario = 30m
                        },
                        new
                        {
                            ProductoId = 6,
                            Costo = 25m,
                            Descripcion = "Pepsi",
                            Inventario = 150m
                        });
                });

            modelBuilder.Entity("PedidosSuplidores_Blazor.Models.Suplidores", b =>
                {
                    b.Property<int>("SuplidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("SuplidorId");

                    b.ToTable("Suplidores");

                    b.HasData(
                        new
                        {
                            SuplidorId = 1,
                            Nombres = "Eufemio Vargas"
                        });
                });

            modelBuilder.Entity("PedidosSuplidores_Blazor.Models.OrdenesDetalle", b =>
                {
                    b.HasOne("PedidosSuplidores_Blazor.Models.Ordenes", null)
                        .WithMany("Detalle")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PedidosSuplidores_Blazor.Models.Ordenes", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
